config/routes.rb
Rails.application.routes.draw do
  get 'profile/:user_id', to: 'profile#profile', as: 'profile'
  get 'dashboard/index'
  get 'feed/index'
  devise_for :users
  resources :posts do
		resources :comments do
      patch :accept, on: :member
      patch :deny, on: :member
    end
    patch :up_vote, on: :member
    patch :down_vote, on: :member
	end
  resources :relationships, only: [:create, :destroy]

	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :post
  belongs_to :user, optional: true

  scope :accepted, -> {where(accepted: true)}

  def commenter
    if self.user 
      user.username
    else
      'Unknown User'
    end
  end 

  def status
    if accepted
      'Public'
    else
      'Private'
    end
  end

  def accepted_default
    self.accepted = false
  end  
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :content, presence: true

	has_many :comments
	belongs_to :user

	scope :availables, -> {where(visible: true)}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy, inverse_of: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy, inverse_of: :followed

  has_many :following, through: 'active_relationships', source: 'followed'
  has_many :followers, through: 'passive_relationships', source: 'follower'

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up) do |u|
					u.permit :email, :username, :password, :password_confirmation
			end
			
			devise_parameter_sanitizer.permit(:account_update) do |u|
					u.permit :email, :username, :password, :current_password
			end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    @comment.update(user: current_user)

    redirect_to @post
  end

  def accept
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    
    @comment.update!(accepted: true)

    redirect_to post_comments_path
  end

  def deny
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    
    @comment.update!(accepted: false)

    redirect_to post_comments_path
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  # def accept
  #   @comment = Comment.find(params[:id])
  #   @comment.update!(accept: true)
  # end

  private

  def comment_params
    params.require(:comment).permit(:title, :content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
		@posts = Post.where("user_id IN (?)", current_user.following_ids).availables.order(created_at: :desc)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :is_user?, only: %i[ edit update destroy ]

  def is_user?
    unless current_user == @post.user
      redirect_to root_path 
    end
  end
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def up_vote
    @post = Post.find(params[:id])
    
    @post.update!(vote_count: @post.vote_count + 1)
  end

  def down_vote
    @post = Post.find(params[:id])
    
    @post.update!(vote_count: @post.vote_count - 1)
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :visible)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = User.find(params[:user_id])
    @posts = @user.posts.availables
    @comments = @user.comments
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

	def create
		@user = User.find(params[:followed_id])
		current_user.follow(@user)

		respond_to do |format|
			format.html {redirect_to profile_path(@user.id)}
			format.js
		end

		
	end

	def destroy
		@user = Relationship.find(params[:id]).followed
		current_user.unfollow(@user)
		
		respond_to do |format|
			format.html {redirect_to profile_path(@user.id)}
			format.js
		end

		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.availables.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/index.html.erb
<div class="jumbotron text-center">
  <h1><%= @post.title %> Comments</h1>
</div>

<ul>
  <% @comments.each do |comment| %>
    <div class="container p-3 my-3 rounded", style="border:1px solid #000000;"> 
      <h4><b><%= comment.status %> Comment titled:</b>  <%= link_to comment.title, post_comment_path(@post, comment) %> written by <%= comment.commenter %>.
      Approve or Deny by clicking the title.</h4>
    </div>
  <% end %>
</ul>

app/views/comments/show.html.erb
<div class="container p-3 my-3 rounded", style="border:1px solid #000000;"> 
	<div class="jumbotron text-center">
  	<h1><%= @comment.title %></h1>
		<hr>
	</div>
	
	<h4><%= @comment.content %></h4><hr>

	<h6 style="text-align:center">Written by <%= @comment.commenter %></h6>
	<div class="jumbotron text-center">
		<% if @comment.accepted %>
			<p>Approved | <%= link_to 'Deny', deny_post_comment_path(@comment.post, @comment), method: :patch %></p>
		<% else %>
			<%= link_to 'Approve', accept_post_comment_path(@comment.post, @comment), method: :patch %>
		<% end %>
	</div>
</div>

app/views/dashboard/index.html.erb
<div class="jumbotron text-center">
  <h1>My Posts</h1>
</div>

<hr>
<br><br>

<% unless current_user.posts.empty?%>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Visible</th>
      <th>Comment Count</th>
      <th>Vote Count</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content.truncate(100) %></td>
        <td><%= post.visible %></td>
        
        <td><%= link_to "(#{post.comments.count}) Comments", post_comments_path(post) %></td>
        <td><%= post.vote_count %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<div class="jumbotron text-center">
  <%= link_to 'Create Post', new_post_path %>
</div>

app/views/feed/index.html.erb
<div class="jumbotron text-center">
  <h1>Followed Users and Articles</h1>
  <hr>
</div>

  <% @posts.each do |post| %>
    <div class="container p-3 my-3 rounded", style="border:1px solid #000000;"> 
      <% if user_signed_in? %>
        <h2 style="text-align:center"><%= link_to post.title.upcase, post_path(post) %></h2> 
        <br>
        <h4> <%= post.content.truncate(300) %></h4>
        <hr>
        <h6 class="text-center">Vote count: <%= post.vote_count %></h6>
        <h6 class="text-center">Added by: <%= link_to post.user.username, profile_path(post.user) %></h6>
      </div>
    <% end %>
  <% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="jumbotron text-center">
  <h1> Editing <%= @post.title %> </h1>
</div>


<div class="container p-3 my-3 rounded", style="border:1px solid #000000;"> 
	<%= render 'form', post: @post %>
</div>


<div class="jumbotron text-center">
	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', dashboard_index_path %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Created by</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<div class="jumbotron text-center">
  <h1>New Post</h1>
  <hr>
</div>
<div class="container p-3 my-4 rounded", style="border:1px solid #000000; width:500px"> 
  <div style="text-align:center">
    <%= render 'form', post: @post %>
    <%= link_to 'Back', dashboard_index_path %>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron text-center">
  <h1><%= @post.title %> </h1>
</div>

<hr />

<div class="jumbotron">
  <p>
    <h2><strong>Content:</strong></h2>
    <h4><%= @post.content %></h4>
  </p>
</div>

<hr />

<h2><strong>Vote Count (<%= @post.vote_count%>)</strong></h2>
<% unless @post.user == current_user%>
  <h4> <%= link_to 'Upvote', up_vote_post_path(@post), method: :patch %> | <%= link_to 'Downvote', down_vote_post_path(@post), method: :patch %></h4>
<% end %>

<hr />

<h2 style="text-align:center"><strong>Comments</strong></h2>


  <% if @post.comments.accepted.any? %>
    <% @post.comments.each do |comment| %>
      <div class="container p-3 my-3 rounded", style="border:1px solid #000000; width:500px"> 
        <% if comment.accepted %>
          <h6 style="text-align:center"><%= comment.title %></h6>
          <h6><%= comment.content %></h6>
          <h6 style="text-align:center">By <%= comment.commenter %></h6>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p> There is no comment yet.</p>
  <% end %>


<hr>

<% unless @post.user == current_user%>
  <div class="container p-3 my-3 rounded", style="border:1px solid #000000; width:500px"> 
    <div class="text-center">
      <h2><strong>Add Comments</strong></h2>

      <%= form_with model: [@post, @post.comments.build] do |form| %>

        <p>
          <strong><%= form.label :title %></strong>
          <%= form.text_field :title %>
        </p>

        <p>
          <strong><%= form.label :content %></strong>
          <%= form.text_area :content %>
        </p>

        <p>
        <%= form.submit %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

<div class="jumbotron text-center">
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', dashboard_index_path %>
</div>

app/views/relationships/create.js.erb
$('#follow_form').html("<%= escape_javascript(render('profile/unfollow')) %>");
$('#followers').html("<h3>Following: <%= @user.following.count %></h3> <h3>Followers: <%= @user.followers.count %></h3>");

app/views/relationships/destroy.js.erb
$('#follow_form').html("<%= escape_javascript(render('profile/follow')) %>");
$('#followers').html("<h3>Following: <%= @user.following.count %></h3> <h3>Followers: <%= @user.followers.count %></h3>");

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'MediumLike', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        	<% if user_signed_in? %> <%= link_to 'Dashboard', dashboard_index_path, class: "nav-link active" %> <% end %>
        </li>

        <li class="nav-item">
        	<% if user_signed_in? %> <%= link_to 'Profile', profile_path(current_user), class: "nav-link active" %> <% end %>
        </li>

				<li class="nav-item">
        	<% if user_signed_in? %> <%= link_to 'Feedpage', feed_index_path , class: "nav-link active" %> <% end %>
        </li>

					<% if user_signed_in? %>
						<li class="nav-item ">
							<%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link active" %> 
						</li>
						<li class="nav-item">
							<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link active" %> 
						</li>

						<% else %>
						<li class="nav-item">
							<%= link_to 'Sign up', new_user_registration_path, class: "nav-link active" %> 
						</li>
						<li class="nav-item">
							<%= link_to 'Login', new_user_session_path, class: "nav-link active" %> 
						</li>			
					<% end %>   
      </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to MediumLike</h1>
  <br><br>
  <h2>Here is the lastest posts!</h2>
  <hr>
</div>



<% @posts.each do |post| %>
  <div class="container p-3 my-3 rounded", style="border:1px solid #000000;"> 
    <% if user_signed_in? %>
      <h2 style="text-align:center"><%= link_to post.title.upcase, post_path(post) %></h2>
      <h4> <%= post.content.truncate(500) %> </h4>
      <br>
      <h6 style="text-align:center"> By: <%= link_to post.user.username, profile_path(post.user) %> </h6> 
    <% else %>
      <h2>"<%= post.title %>" by <%= post.user.username %></h2>
    <% end %>
  </div>
<% end %>

<% unless user_signed_in? %>
  <div class="jumbotron text-center">
    <h2>Sign Up or Login to Access more</h2>
  </div>
<% end %>
      